name: iosmobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  equatable: ^2.0.5
  intl: ^0.19.0
  calendar_day_view: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets (imÃ¡genes y recursos)
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/utimee.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icons/utimee.png"
    background_color: "#7209B7"
    theme_color: "#7209B7"
  windows:
    generate: true
    image_path: "assets/images/icons/utimee.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icons/utimee.png"
