name: iosmobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_bloc: ^9.1.1

  # CORRECCIÓN: Versión actualizada para ser compatible con Flutter 3.9.2+
  syncfusion_flutter_calendar: ^31.2.5

  # CORRECCIÓN: Versión actualizada que va bien con la última de syncfusion
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true